apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nodejs-backend-config
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /healthz
